In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt       # Standard plotting library


# Pretty display for notebooks
%matplotlib inline

# Load the Boston housing dataset
X = pd.read_csv('data/application_train_final.csv')#application_train_final.csv')
train_size_ = X.shape[0]
Y = pd.read_csv('data/application_test_final.csv')

# Success - Display the first record
display(Y.head(n=5))

,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,CNT_CHILDREN,CNT_FAM_MEMBERS,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_ID_PUBLISH,DAYS_LAST_PHONE_CHANGE,...,ORGANIZATION_TYPE_Transport: type 4,ORGANIZATION_TYPE_University,ORGANIZATION_TYPE_XNA,WEEKDAY_APPR_PROCESS_START_FRIDAY,WEEKDAY_APPR_PROCESS_START_MONDAY,WEEKDAY_APPR_PROCESS_START_SATURDAY,WEEKDAY_APPR_PROCESS_START_SUNDAY,WEEKDAY_APPR_PROCESS_START_THURSDAY,WEEKDAY_APPR_PROCESS_START_TUESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY
0,0.528004,0.418825,0.372361,0.175468,0.00,0.05,0.461908,0.176530,0.927609,0.400138,...,0,0,0,1,0,0,0,0,0,0
1,0.524353,0.511705,0.522877,0.231252,0.10,0.15,0.853278,0.043881,0.669029,0.846136,...,0,0,0,1,0,0,0,0,0,0
2,0.426455,0.413755,0.380878,0.188919,0.10,0.15,0.604606,0.103059,0.268584,0.511580,...,0,0,0,0,0,0,0,1,0,0
3,0.656975,0.621675,0.595941,0.297672,0.15,0.20,0.643452,0.236880,0.382659,0.798899,...,0,0,0,0,0,0,0,1,0,0
4,0.432603,0.357666,0.372361,0.122499,0.00,0.05,0.506903,0.263287,0.395581,0.649163,...,0,0,0,0,0,0,0,0,1,0

In [76]:
import xgboost as xgb
from xgboost.sklearn import XGBClassifier
from sklearn import cross_validation, metrics   #Additional scklearn functions
from sklearn.grid_search import GridSearchCV   #Perforing grid search

import matplotlib.pylab as plt
%matplotlib inline
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 12, 4

X = X.drop('SK_ID_CURR', axis=1)
X.dropna(subset=['TARGET'], inplace=True)
target = X['TARGET']
train = X.drop('TARGET', axis = 1)

In [74]:
clf = XGBClassifier(max_depth=6, learning_rate=0.1,n_estimators=100,
                      n_jobs=16,scale_pos_weight=4,missing=np.nan,gamma=16,
                      eval_metric="auc",reg_lambda=40,reg_alpha=40)
clf = clf.fit(X_train, y_train)
predict = clf.predict(X_test)
tn, fp, fn, tp = confusion_matrix(y_test, predict).ravel()
print(tn, fp, fn, tp)

#scores = cross_val_score(model, train, target, cv=2, scoring='f1')

#print(scores)

81375 3366 6250 1175

/Users/omar/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [36]:
clf = XGBClassifier(max_depth=6, learning_rate=0.1,n_estimators=100,
                      n_jobs=16,scale_pos_weight=4,missing=np.nan,gamma=16,
                      eval_metric="auc",reg_lambda=40,reg_alpha=40)
clf = clf.fit(X_train, y_train)
predict = clf.predict(X_test)
tn, fp, fn, tp = confusion_matrix(y_test, predict).ravel()
print(tn, fp, fn, tp)

#scores = cross_val_score(model, train, target, cv=2, scoring='f1')

#print(scores)

81375 3366 6250 1175

/Users/omar/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [61]:
clf = XGBClassifier(max_depth=12, learning_rate=0.1,n_estimators=100,
                      n_jobs=16,scale_pos_weight=4,missing=np.nan,gamma=16,
                      eval_metric="auc",reg_lambda=40,reg_alpha=40)
clf = clf.fit(X_train[:20000], y_train[:20000])
predict = clf.predict(X_test[:20000])
tn, fp, fn, tp = confusion_matrix(y_test[:20000], predict).ravel()
print(tn, fp, fn, tp)

#scores = cross_val_score(model, train, target, cv=2, scoring='f1')

#print(scores)

18067 326 1489 118

/Users/omar/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [68]:
clf = SVC()
clf = clf.fit(X_train[:20000], y_train[:20000])
predict = clf.predict(X_test[:20000])
tn, fp, fn, tp = confusion_matrix(y_test[:20000], predict).ravel()
print(tn, fp, fn, tp)

#scores = cross_val_score(model, train, target, cv=2, scoring='f1')

#print(scores)

18393 0 1607 0